baseURL: https://sysfig.dev
enableGitInfo: true
frontmatter:
  date:
  - date
  expiryDate:
  - expiryDate
  lastmod:
  - :fileModTime
  - :git
  publishDate:
  - publishDate
languageCode: en-US
theme: sysfig
title: sysfig
